# Generated by Django 4.1.7 on 2023-06-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
