# Generated by Django 4.1.7 on 2023-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_catdb_price_catdb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdb',
            name='Temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catdb',
            name='Varieties',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='catdb',
            name='Vin',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
