# Generated by Django 4.1.7 on 2023-06-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_catdb_temp_catdb_varieties_catdb_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catdb',
            name='Temp',
        ),
    ]
