# Generated by Django 4.1.7 on 2023-06-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_remove_catdb_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catdb',
            name='Quantity',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
