# Generated by Django 4.1.7 on 2023-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=70, null=True)),
                ('Email', models.EmailField(blank=True, max_length=70, null=True)),
                ('Password', models.CharField(blank=True, max_length=70, null=True)),
                ('Cpass', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
