# Generated by Django 4.1.7 on 2023-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(blank=True, max_length=40, null=True)),
                ('Last', models.CharField(blank=True, max_length=40, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Street', models.CharField(blank=True, max_length=60, null=True)),
                ('Postal', models.IntegerField(blank=True, null=True)),
                ('Town', models.CharField(blank=True, max_length=60, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
