# Generated by Django 4.1.7 on 2023-07-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_checkout_grat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Tot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Grat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
