# Generated by Django 4.1.7 on 2023-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_alter_cartdb_tot_alter_checkout_grat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Grat',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
